services:
  odoo:
    image: odoo:17.0
    container_name: pfm-odoo
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./volumes/addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
      - DBNAME=${POSTGRES_DB}
    ports:
      - "${ODOO_EXPOSED_PORT}:8069"
  db:
    image: postgres:15
    container_name: pfm-db
    restart: always
    ports:
      - "${POSTGRES_EXPOSED_PORT}:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data: